# Generated by Django 3.0.6 on 2020-05-28 07:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('deleted user'), related_name='referrer', to=settings.AUTH_USER_MODEL),
        ),
    ]
