# Generated by Django 3.0.6 on 2020-05-28 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_auto_20200528_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referred',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
